version: '3.1'

services:
  postgres:
    image: postgres:10.7-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - "54320:5432"
    volumes:
      - ./test-data:/docker-entrypoint-initdb.d

  # mysql:
  #   image: mysql:5.6
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: test
  #     MYSQL_DATABASE: test
  #   ports:
  #     - "33060:3306"
