name: CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Build the docker-compose stack
        run: docker-compose up --build -d
      - name: Check running containers
        run: docker ps -a
      - name: Install Dependencies
        run: npm install
      - name: Bootstrap packages
        run: npm run bootstrap
      - name: Execute test
        run: npm run test
      - name: Upload coverage
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage
