name: master

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: npm install
      - name: Bootstrap packages
        run: npm run bootstrap
      - name: Execute test
        run: npm run ci
      - name: Upload coverage
        uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage

  lint:
    name: Code Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 10.x
      - name: Install Dependencies
        run: npm install
      - name: Execute lint
        run: npm run lint
